blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/Loghorn/CppWindowsCommunityToolkit/discussions/categories/questions-help
    about: I have a question about how to use something in the toolkit.
